services:
  mysql:
    image: mysql:8

    container_name: mysql-container

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: librarydb
      MYSQL_USER: libraryuser
      MYSQL_PASSWORD: password123

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

  library-app:
    build: .

    container_name: library-management-app

    ports:
      - "9090:8080"

    depends_on:
      - mysql

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/librarydb
      SPRING_DATASOURCE_USERNAME: libraryuser
      SPRING_DATASOURCE_PASSWORD: password123

volumes:
  mysql-data:
